import { Injectable, computed, effect, signal } from '@angular/core';
import { BackendApiService } from './backend-api.service';
import { Product } from './product.model';
export interface CartVariant { color?: string; size?: string; sku?: string; price?: number; oldPrice?: number; image?: string; stock?: number; }
export interface CartItem { product: Product; quantity: number; variant?: CartVariant; }
export interface ShippingConfig { freeShippingThreshold:number; prepaidShippingCharge:number; codShippingCharge:number; codMaxOrderAmount:number; codEnabled:boolean; }
export interface CartCharges { subtotal:number; productDiscount:number; couponDiscount:number; shippingCost:number; gst:number; platformFee:number; handlingFee:number; convenienceFee:number; giftWrapFee:number; totalSavings:number; total:number; }
@Injectable({providedIn:'root'}) export class CartService {
 private readonly items=signal<CartItem[]>(this.load()); readonly cart=this.items.asReadonly();
 readonly shippingConfig=signal<ShippingConfig>({freeShippingThreshold:200,prepaidShippingCharge:20,codShippingCharge:70,codMaxOrderAmount:2000,codEnabled:true}); readonly shippingConfigLoaded=signal(false);
 constructor(private api:BackendApiService){void this.loadShippingConfig();effect(()=>{if(!this.codAllowed()&&this.paymentMethod()==='COD')this.paymentMethod.set('RAZORPAY');});}
 readonly count=computed(()=>this.items().reduce((s,i)=>s+Math.max(0,i.quantity),0)); private itemPrice(i:CartItem){return Math.max(0,Number(i.variant?.price??i.product.price)||0);} private itemOldPrice(i:CartItem){return Math.max(this.itemPrice(i),Number(i.variant?.oldPrice??i.product.oldPrice)||this.itemPrice(i));}
 readonly subtotal=computed(()=>this.items().reduce((s,i)=>s+this.itemPrice(i)*Math.max(0,Number(i.quantity)||0),0)); readonly couponCode=signal(''); readonly giftWrap=signal(false); readonly paymentMethod=signal<'COD'|'RAZORPAY'>('COD');
 setPaymentMethod(m:'COD'|'RAZORPAY'){if(m==='COD'&&!this.codAllowed()){this.paymentMethod.set('RAZORPAY');return;}this.paymentMethod.set(m);}
 readonly productDiscount=computed(()=>Math.round(this.items().reduce((s,i)=>s+Math.max(0,this.itemOldPrice(i)-this.itemPrice(i))*Math.max(0,i.quantity),0))); readonly couponDiscount=computed(()=>this.couponCode().trim().toUpperCase()==='WISS10'?Math.round(this.subtotal()*.1):0); readonly payableProducts=computed(()=>Math.max(0,this.subtotal()-this.couponDiscount()));
 readonly codAllowed=computed(()=>{const c=this.shippingConfig();return c.codEnabled&&this.payableProducts()<=Math.max(0,Number(c.codMaxOrderAmount)||0);}); readonly codUnavailableReason=computed(()=>{const c=this.shippingConfig();if(!c.codEnabled)return 'Cash on Delivery is currently unavailable.';const m=Math.max(0,Number(c.codMaxOrderAmount)||0);return this.payableProducts()>m?`COD is unavailable above ₹${m.toLocaleString('en-IN')}. Please choose prepaid payment.`:'';});
 readonly shippingCost=computed(()=>this.shippingFor(this.paymentMethod())); readonly platformFee=computed(()=>0); readonly handlingFee=computed(()=>0); readonly convenienceFee=computed(()=>0); readonly giftWrapFee=computed(()=>this.giftWrap()&&this.subtotal()>0?49:0); readonly taxableAmount=computed(()=>Math.max(0,this.subtotal()-this.couponDiscount()+this.shippingCost()+this.giftWrapFee())); readonly gst=computed(()=>0); readonly totalSavings=computed(()=>this.productDiscount()+this.couponDiscount()); readonly total=computed(()=>this.totalFor(this.paymentMethod())); readonly codTotal=computed(()=>this.totalFor('COD')); readonly razorpayTotal=computed(()=>this.totalFor('RAZORPAY')); readonly razorpaySavings=computed(()=>Math.max(0,this.codTotal()-this.razorpayTotal()));
 shippingFor(m:'COD'|'RAZORPAY'){const p=this.payableProducts(),c=this.shippingConfig();if(p<=0||p>=Math.max(0,Number(c.freeShippingThreshold)||0))return 0;return m==='COD'?Math.max(0,Number(c.codShippingCharge)||0):Math.max(0,Number(c.prepaidShippingCharge)||0);} totalFor(m:'COD'|'RAZORPAY'){return Math.max(0,Math.round(this.payableProducts()+this.shippingFor(m)+this.giftWrapFee()));}
 readonly summary=computed<CartCharges>(()=>({subtotal:this.subtotal(),productDiscount:this.productDiscount(),couponDiscount:this.couponDiscount(),shippingCost:this.shippingCost(),gst:this.gst(),platformFee:this.platformFee(),handlingFee:this.handlingFee(),convenienceFee:this.convenienceFee(),giftWrapFee:this.giftWrapFee(),totalSavings:this.totalSavings(),total:this.total()}));
 private key(id:string|number,v?:CartVariant){return `${id}::${v?.sku||`${v?.color||''}|${v?.size||''}`}`;}
 add(product:Product,variant?:CartVariant){if(!product?.id)return;const k=this.key(product.id,variant);const cartProduct:any=variant?{...product,price:variant.price??product.price,oldPrice:variant.oldPrice??product.oldPrice,image:variant.image||product.image,stock:variant.stock??product.stock,variant}:product;this.items.update(items=>{const i=items.findIndex(x=>this.key(x.product.id,x.variant)===k);if(i<0)return[...items,{product:cartProduct,quantity:1,variant}];const copy=[...items];copy[i]={...copy[i],quantity:Math.max(1,copy[i].quantity+1)};return copy;});this.persist();void this.api.post('/homepage/events/cart-add',{productId:product.id,variantSku:variant?.sku,variantColor:variant?.color,variantSize:variant?.size}).catch(()=>undefined);}
 update(id:string|number,q:number,v?:CartVariant){const n=Math.max(0,Math.floor(Number(q)||0)),k=this.key(id,v);this.items.update(a=>n<=0?a.filter(x=>this.key(x.product.id,x.variant)!==k):a.map(x=>this.key(x.product.id,x.variant)===k?{...x,quantity:n}:x));this.persist();}
 remove(id:string|number,v?:CartVariant){const k=this.key(id,v);this.items.update(a=>a.filter(x=>this.key(x.product.id,x.variant)!==k));this.persist();}
 applyCoupon(c:string){const n=c.trim().toUpperCase();if(n==='WISS10'){this.couponCode.set(n);return true;}this.couponCode.set('');return false;} removeCoupon(){this.couponCode.set('');} setGiftWrap(v:boolean){this.giftWrap.set(!!v);} clear(){this.items.set([]);this.couponCode.set('');this.giftWrap.set(false);this.persist();}
 private async loadShippingConfig(){try{const v:any=await this.api.get('/shipping-config');if(v)this.shippingConfig.set({freeShippingThreshold:Math.max(0,Number(v.freeShippingThreshold)||0),prepaidShippingCharge:Math.max(0,Number(v.prepaidShippingCharge)||0),codShippingCharge:Math.max(0,Number(v.codShippingCharge)||0),codMaxOrderAmount:Math.max(0,Number(v.codMaxOrderAmount)||0),codEnabled:v.codEnabled!==false});}catch{}finally{this.shippingConfigLoaded.set(true);if(!this.codAllowed())this.paymentMethod.set('RAZORPAY');}}
 private persist(){try{localStorage.setItem('wissfind-cart',JSON.stringify(this.items()));}catch{}}
 private load():CartItem[]{try{const raw=localStorage.getItem('wissfind-cart');if(!raw)return[];const p=JSON.parse(raw);if(!Array.isArray(p))return[];return p.filter(x=>x&&x.product&&x.product.id&&Number(x.quantity)>0).map(x=>({product:x.product as Product,quantity:Math.max(1,Math.floor(Number(x.quantity))),variant:x.variant?x.variant as CartVariant:undefined}));}catch{return[];}}
}
