import { Component, HostListener, computed, inject, signal, OnDestroy } from '@angular/core';
import { DecimalPipe, NgFor, NgIf } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ProductService } from '../core/product.service';
import { ReviewService } from '../core/review.service';
import { CartService } from '../core/cart.service';

@Component({standalone:true,imports:[NgFor,NgIf,DecimalPipe,RouterLink],template:`<main class="page"><div class="container"><section id="shop"><div class="grid"><article class="product-card" *ngFor="let p of pagedProducts()"><a [routerLink]="['/product',p.id]" class="image-wrap"><img [src]="p.image" [alt]="p.name"><span *ngIf="p.oldPrice" class="sale">SALE</span></a><div class="product-info"><h3><a [routerLink]="['/product',p.id]">{{p.name}}</a></h3><div class="price-row"><div class="price"><strong>₹{{p.price|number}}</strong><del *ngIf="p.oldPrice">₹{{p.oldPrice|number}}</del></div><button type="button" class="add-cart" (click)="addToCart($event,p)" [disabled]="!p.stock">{{p.stock?'Add to cart':'Out of stock'}}</button></div></div></article></div></section></div></main>`})
export class HomeComponent implements OnDestroy {
@HostListener('window:wissfind-category-change',['$event']) onHeaderCategoryChange(e:Event){const c=(e as CustomEvent).detail as any;if(this.topCategories.includes(c))this.selectCategory(c)}
private readonly productService=inject(ProductService);private readonly cart=inject(CartService);private readonly router=inject(Router);private products=this.productService.products;private readonly pageAbort=new AbortController();readonly reviews=inject(ReviewService);private route=inject(ActivatedRoute);query=signal('');category=signal<any>('All');subcategory=signal('All');detail=signal('All');sort=signal('featured');page=signal(1);readonly pageSize=8;readonly topCategories=['All','Fashion','Electronics','Home & Living','Beauty','Sports & Fitness','Books & Stationery','Grocery','Travel'];
constructor(){void this.productService.load(this.pageAbort.signal);this.route.queryParamMap.subscribe(p=>{this.query.set((p.get('q')||'').toLowerCase());this.page.set(1)})}ngOnDestroy(){this.pageAbort.abort()}
selectCategory(c:any){this.category.set(c);this.subcategory.set('All');this.detail.set('All');this.page.set(1)}selectSubcategory(v:string){this.subcategory.set(v);this.detail.set('All');this.page.set(1)}selectDetail(v:string){this.detail.set(v);this.page.set(1)}changeSort(v:string){this.sort.set(v);this.page.set(1)}setPage(v:number){this.page.set(Math.min(Math.max(v,1),this.pageCount()))}
subcategoriesFor(c:any){return []}displaySubcategory(v:string){return v}detailCategoriesFor(c:any,s:string){return []}matchesSubcategory(p:any){return this.subcategory()==='All'||p.subcategory===this.subcategory()}matchesDetail(p:any){return this.detail()==='All'||p.type===this.detail()}
addToCart(e:Event,p:any){e.preventDefault();e.stopPropagation();if(!p?.stock)return;this.cart.add(p);void this.router.navigateByUrl('/cart')}
starText(r:number){const f=Math.round(r);return '★'.repeat(f)+'☆'.repeat(5-f)}toggleLike(e:Event,id:string){e.preventDefault();e.stopPropagation();this.reviews.toggleProductLike(id)}
filtered=computed(()=>{this.productService.productsVersion();let l=this.products.filter((p:any)=>this.category()==='All'||p.category===this.category());const q=this.query();if(q)l=l.filter((p:any)=>`${p.name} ${p.category} ${p.subcategory} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q));switch(this.sort()){case'low':return[...l].sort((a,b)=>a.price-b.price);case'high':return[...l].sort((a,b)=>b.price-a.price);case'rating':return[...l].sort((a,b)=>b.rating-a.rating);default:return l}});pageCount=computed(()=>Math.max(1,Math.ceil(this.filtered().length/this.pageSize)));pageNumbers=computed(()=>Array.from({length:this.pageCount()},(_,i)=>i+1));pagedProducts=computed(()=>{const s=(this.page()-1)*this.pageSize;return this.filtered().slice(s,s+this.pageSize)})}
