import { CommonModule } from '@angular/common';
import { Component, Input, inject } from '@angular/core';
import { BackendApiService } from '../core/backend-api.service';

@Component({standalone:true,selector:'app-product-variant-selector',imports:[CommonModule],template:`
<section class="variant-panel" *ngIf="variants.length"><div class="title"><b>Choose your variant</b><button type="button" (click)="collapsed=!collapsed">{{collapsed?'⌃':'⌄'}}</button></div><ng-container *ngIf="!collapsed"><div class="label">Color</div><div class="choices color-choices"><button *ngFor="let color of variants" type="button" [class.selected]="selectedColor===color" (click)="chooseColor(color)"><span class="dot" [style.background]="colorName(color.color)"></span>{{color.color}}</button></div><div class="label">Size</div><div class="choices"><button *ngFor="let size of (selectedColor?.sizes||[])" type="button" [disabled]="size.stock<=0" [class.selected]="selectedSize===size" (click)="chooseSize(size)">{{size.size}}</button></div><div class="summary" *ngIf="selectedSize"><span>{{selectedColor.color}} / {{selectedSize.size}}</span><b>₹{{selectedSize.price|number}}</b><small>{{selectedSize.stock>0?selectedSize.stock+' left':'Out of stock'}}</small></div></ng-container></section>`,styles:[`.variant-panel{position:fixed;right:24px;bottom:24px;z-index:50;width:310px;background:#fff;border:1px solid #dedfe3;border-radius:16px;box-shadow:0 18px 50px rgba(0,0,0,.16);padding:14px}.title{display:flex;justify-content:space-between;align-items:center}.title button{border:0;background:#f4f4f2;border-radius:50%;width:28px;height:28px;cursor:pointer}.label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#777;font-weight:800;margin:13px 0 7px}.choices{display:flex;gap:7px;flex-wrap:wrap}.choices button{border:1px solid #ddd;background:#fff;border-radius:9px;padding:8px 11px;cursor:pointer}.choices button.selected{border-color:#111;box-shadow:0 0 0 1px #111}.choices button:disabled{opacity:.35}.color-choices button{display:flex;align-items:center;gap:6px}.dot{width:14px;height:14px;border-radius:50%;border:1px solid #bbb}.summary{margin-top:12px;padding:10px;border-radius:10px;background:#f7f7f4;display:grid;grid-template-columns:1fr auto;gap:3px}.summary small{grid-column:1/-1;color:#777}@media(max-width:600px){.variant-panel{left:12px;right:12px;bottom:12px;width:auto}}`]})
export class ProductVariantSelectorComponent { @Input({required:true}) product!:any; private api=inject(BackendApiService); variants:any[]=[]; selectedColor:any=null; selectedSize:any=null; collapsed=false;
 async ngOnInit(){try{this.variants=await this.api.get<any[]>(`/products/${this.product.id}/variants`)||[];if(this.variants.length)this.chooseColor(this.variants[0]);}catch{this.variants=[];}}
 chooseColor(color:any){this.selectedColor=color;this.selectedSize=(color.sizes||[]).find((x:any)=>x.stock>0)||color.sizes?.[0]||null;this.applySelection();}
 chooseSize(size:any){if(size.stock<=0)return;this.selectedSize=size;this.applySelection();}
 applySelection(){if(!this.product||!this.selectedColor||!this.selectedSize)return;this.product.variantId=this.selectedSize.id;this.product.variantLabel=`${this.selectedColor.color} / ${this.selectedSize.size}`;this.product.sku=this.selectedSize.sku;this.product.price=Number(this.selectedSize.price||0);this.product.oldPrice=Number(this.selectedSize.oldPrice||0)||undefined;this.product.stock=Number(this.selectedSize.stock||0);const images=(this.selectedColor.images||[]).filter(Boolean);if(images.length){this.product.images=images;this.product.image=images[0];}}
 colorName(name:string){const map:any={black:'#111',white:'#fff',red:'#e53935',blue:'#1e88e5',green:'#43a047',yellow:'#fdd835',pink:'#ec407a',purple:'#8e24aa',orange:'#fb8c00',grey:'#9e9e9e',gray:'#9e9e9e',brown:'#795548',beige:'#d7c3a5',gold:'#d4af37',silver:'#c0c0c0'};return map[String(name||'').toLowerCase()]||'#ddd';}
}
